#! /bin/bash

output="ng.plugin.zsh"

echo "# Autogenerated from ng help " > $output

printAllOptions() {
  name=$1
  opts=$2

  opts_string=""
  for opt in $2
  do
    opts_string="$opt $opts_string"
  done
  echo "${name}_opts='$opts_string'" >> $output
}

ng_opts=$(ng help | grep '^  ' | cut -d ' ' -f 3)
printAllOptions "ng" "${ng_opts[@]}"


for arg in $ng_opts
do
  echo "Generate ng $arg"
  sub_opts=()
  if [ $arg = "generate" ]
  then
    sub_opts+=$(ng $arg --help | sed -E -n 's/^\s{4}(\w*)$/\1/p')
  fi
  sub_opts+=$(ng $arg --help | grep -Eo '\-\-[a-zA-Z0-9-]+')
  printAllOptions "$arg" "${sub_opts[@]}"
done

cat functions.template >> $output
